# Generated by Django 4.2.2 on 2023-06-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='псевдоним')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Остальное'), (1, 'Женщина'), (2, 'Мужчина')], default=0, verbose_name='гендер')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'музыкант',
                'verbose_name_plural': 'музыканты',
                'ordering': ('id',),
            },
        ),
    ]
