# Generated by Django 4.2.2 on 2023-07-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='фоловеры')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.band', verbose_name='исполнитель'),
        ),
    ]
