# Generated by Django 4.2.2 on 2023-07-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_artist_datetime_created_artist_datetime_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название альбома')),
                ('release_date', models.DateTimeField(verbose_name='дата релиза')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='логотип')),
                ('status', models.SmallIntegerField(choices=[(0, 'Обычный'), (1, 'Серебряный'), (2, 'Золотой'), (3, 'Платиновый')], default=0, verbose_name='статус')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.band', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
                'ordering': ('release_date',),
            },
        ),
    ]
