# Generated by Django 4.2.2 on 2023-07-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='логотип'),
        ),
    ]
