# Generated by Django 4.2.2 on 2023-07-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_album_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название песни')),
                ('audio_file', models.FileField(upload_to='', verbose_name='аудио файл')),
                ('duration', models.DurationField(verbose_name='длительность трека')),
                ('times_played', models.PositiveIntegerField(blank=True, null=True, verbose_name='количество прослушиваний')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album', verbose_name='альбом')),
                ('genre', models.ManyToManyField(to='main.genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'песни',
                'ordering': ('id',),
            },
        ),
    ]
