# Generated by Django 4.2.2 on 2023-07-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.country', verbose_name='страна'),
        ),
    ]
